"""Create table Balance

Revision ID: e41382197197
Revises: eeb7794cb1b4
Create Date: 2021-04-15 22:27:33.707254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41382197197'
down_revision = 'eeb7794cb1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('user_cpf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_cpf'], ['User.cpf'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Balance')
    # ### end Alembic commands ###
