"""Alter table user

Revision ID: eeb7794cb1b4
Revises: 2f76ba9fa308
Create Date: 2021-04-14 20:05:49.145527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb7794cb1b4'
down_revision = '2f76ba9fa308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
